#+ summary: Get the nanopublications referring to a given paper.
#+ method: GET
#+ pagination: 1000
#+ endpoint_in_url: False

prefix np: <http://www.nanopub.org/nschema#>
prefix npa: <http://purl.org/nanopub/admin/>
prefix npx: <http://purl.org/nanopub/x/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix dct: <http://purl.org/dc/terms/>
prefix oa: <http://www.w3.org/ns/oa#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select distinct ?user (count(?subj) as ?assertiontriples) ?thing ?thingLabel ?date where {
  # (sample(?subj) as ?subjSample) (sample(?rel) as ?relSample) (sample(?obj) as ?objSample)
  graph npa:networkGraph {
     ?_nanopub_iri npx:supersedes{0} ?np .
  }
  graph npa:graph {
    ?_nanopub_iri npa:hasHeadGraph ?h .
    ?_nanopub_iri dct:created ?date .
    ?_nanopub_iri npa:hasValidSignatureForPublicKey ?pubkey .
  }
  graph ?h {
    ?_nanopub_iri np:hasAssertion ?a .
    ?_nanopub_iri np:hasPublicationInfo ?i .
  }
  graph ?a {
    ?subj ?rel ?obj .
    optional { ?thing rdfs:label ?thingLabel. }
  }
  graph ?i {
    ?_nanopub_iri dct:creator ?user .
    optional { ?_nanopub_iri npx:introduces ?thing . }
  }
} group by ?_nanopub_iri ?user ?thing ?thingLabel ?date
